name: Build Electron Installer
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install --prefix electron
      - name: Build installer
        run: npm run dist --prefix electron
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: PayrollInstaller
          path: electron/dist/*.exe

